version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file:
      - .env
    ports:
      - "8000:8000"

  calculations:
    build:
      context: .
      dockerfile: Dockerfile.calculations
    env_file:
      - .env
